### ISSUE TITLE
Can it be done if I want to insert pair instead of int?

### ISSUE THREAD

**Issue by chakpongchung** [google/btree#17]
https://forum.golangbridge.org/t/how-to-use-github-com-google-btree/4086/3

For example, I want to insert into the btree, and the btree is sorted by v2, without modifying the source code of btree library

So basically I want to do CRUD on the btree(Create a node and then insert, Retrieve the node, Update the node by changing the v2,Delete the node by v1)

It will be better if it can generalize to arbitrary item and sort by certain element.

**Comment by gconnell** [comment]
So long as an object (struct, etc) matches the btree.Item interface, it can be inserted/sorted.
